# Markdown renderer configuration
[goldmark.renderer]
unsafe = true

[goldmark.extensions]
# To avoid a conflict when enabling the “subscript” feature of the Extras extension
strikethrough = false

[goldmark.extensions.passthrough]
enable = true

[goldmark.extensions.extras]
[goldmark.extensions.extras.delete]
enable = true
[goldmark.extensions.extras.insert]
enable = true
[goldmark.extensions.extras.mark]
enable = true
[goldmark.extensions.extras.subscript]
enable = true
[goldmark.extensions.extras.superscript]
enable = true

# LaTeX math support
# https://gohugo.io/content-management/mathematics/
[goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

[tableOfContents]
endLevel = 6
ordered = true
startLevel = 2

[highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
