# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = false
# favicon = "/favicon.ico"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy = "default"

# Edit on GitHub repo
repository = "https://github.com/SunsetMkt/Blog-hugo"

# THEME_VERSION=$(hugo mod graph | grep hugo-theme-stack/v | sed -E 's/.*@v([0-9][^ ]*)/\1/')
# export HUGO_PARAMS_STACK_THEME_VERSION="$THEME_VERSION"
# themeVersion = "{{ getenv `HUGO_PARAMS_STACK_THEME_VERSION` }}" # Not working

[footer]
since = 2019
customText = """\
  本博客内容仅供参考，作者不对其准确性、完整性或适用性作出任何明示或暗示的保证。\
  因使用、引用或解读本博客内容所引发的任何直接或间接后果，作者概不承担任何责任。\
  <br>本博客可能包含第三方转载内容，相关版权归原作者所有。转载内容仅为分享信息之目的，不代表作者观点。如涉及侵权，请联系删除。\
  """

[dateFormat]
published = "2006-01-02"
lastUpdated = "2006-01-02 15:04:05"

[sidebar]
emoji = "🇺🇦"
subtitle = "Sunset Edu. & Tech. Group 的首席程序员"
avatar = "img/avatar2_pride.webp"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = true
default = "除非另有说明，此内容使用 CC BY-SA 4.0 许可。"

[widgets]
homepage = [
    { type = "search" },
    { type = "archives", params = { limit = 5 } },
    { type = "categories", params = { limit = 10 } },
    { type = "tag-cloud", params = { limit = 10 } },
]
page = [{ type = "toc" }]

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = true
local = true
src = "ogimage/og_base.png"
generate = true             # 分支特性：基于 src 图片和页面信息生成 ogimage

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "waline"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = "https://waline.sunmkt.uk"
lang = "zh-CN"
# avatar = ""
emoji = ["https://unpkg.com/@waline/emojis@1.3.0/tw-emoji"]
reaction = [
    "https://unpkg.com/@waline/emojis@1.3.0/tw-emoji/1f60d.png",
    "https://unpkg.com/@waline/emojis@1.3.0/tw-emoji/1f642.png",
    "https://unpkg.com/@waline/emojis@1.3.0/tw-emoji/1f641.png",
    "https://unpkg.com/@waline/emojis@1.3.0/tw-emoji/1f62d.png",
]
requiredMeta = []
search = false
turnstileKey = "0x4AAAAAAAZ0ouYIQ46lj2Up"
pageview = ".waline-pageview-count" # 浏览量统计
comment = ".waline-comment-count" # 评论数统计

[comments.waline.locale]
admin = "Admin"
level0 = 'Level 0'
level1 = 'Level 1'
level2 = 'Level 2'
level3 = 'Level 3'
level4 = 'Level 4'
level5 = 'Level 5'
placeholder = "请参考关于页面中的“关于评论”部分以了解更多。"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = "SunsetMkt/Blog-hugo"
repoID = "R_kgDONNixWA"
category = "Announcements"
categoryID = "DIC_kwDONNixWM4CkLtz"
mapping = "pathname"
lightTheme = "light"
darkTheme = "dark"
reactionsEnabled = 1
emitMetadata = 1

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
