# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "email"
name = "Email"
url = "mailto:hi@sunmkt.uk"

[social.params]
icon = "mail"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/SunsetMkt"

[social.params]
icon = "brand-github"
